import { Track, CalendarEvent } from './store';

// Mock Music Data - 12 Albums
export const mockTracks: Track[] = [
  {
    id: 'track-1',
    title: 'Midnight Echoes',
    artist: 'Luna Shadows',
    album: 'Neon Dreams',
    duration: 243,
    coverColor: '#6B2E8F',
  },
  {
    id: 'track-2',
    title: 'Electric Highway',
    artist: 'The Neon Collective',
    album: 'Synthwave Chronicles',
    duration: 198,
    coverColor: '#FF6B35',
  },
  {
    id: 'track-3',
    title: 'Ocean Drift',
    artist: 'Tidal Wave',
    album: 'Deep Blue',
    duration: 287,
    coverColor: '#0A7C9E',
  },
  {
    id: 'track-4',
    title: 'Velvet Sunrise',
    artist: 'Aurora Grey',
    album: 'Morning Glory',
    duration: 214,
    coverColor: '#D64545',
  },
  {
    id: 'track-5',
    title: 'Neon Lights',
    artist: 'Cyber Dreams',
    album: 'Digital Paradise',
    duration: 256,
    coverColor: '#FF1744',
  },
  {
    id: 'track-6',
    title: 'Cosmic Wanderer',
    artist: 'Starfield',
    album: 'Interstellar',
    duration: 301,
    coverColor: '#1A237E',
  },
  {
    id: 'track-7',
    title: 'Golden Hour',
    artist: 'Sunset Boulevard',
    album: 'California Dreaming',
    duration: 189,
    coverColor: '#FF9800',
  },
  {
    id: 'track-8',
    title: 'Retrograde',
    artist: 'The Parallax',
    album: 'Time Machine',
    duration: 267,
    coverColor: '#8E24AA',
  },
  {
    id: 'track-9',
    title: 'Crystal Clear',
    artist: 'Diamond Eyes',
    album: 'Prism',
    duration: 223,
    coverColor: '#00BCD4',
  },
  {
    id: 'track-10',
    title: 'Thunder Road',
    artist: 'Storm Chasers',
    album: 'Lightning Strikes',
    duration: 295,
    coverColor: '#424242',
  },
  {
    id: 'track-11',
    title: 'Violet Haze',
    artist: 'Purple Reign',
    album: 'Ultraviolet',
    duration: 181,
    coverColor: '#7B1FA2',
  },
  {
    id: 'track-12',
    title: 'Phoenix Rising',
    artist: 'Ember & Ash',
    album: 'Rebirth',
    duration: 276,
    coverColor: '#E64A19',
  },
];

// Helper function to create dates relative to today
const createDate = (daysFromNow: number, hours: number = 0, minutes: number = 0): Date => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hours, minutes, 0, 0);
  return date;
};

// Mock Calendar Events - 20 events spread across 2 weeks
export const mockEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'Team Standup',
    date: createDate(0, 9, 30),
    time: '9:30 AM',
    type: 'meeting',
    description: 'Daily sync with the development team',
  },
  {
    id: 'event-2',
    title: 'Doctor Appointment',
    date: createDate(1, 14, 0),
    time: '2:00 PM',
    type: 'appointment',
    description: 'Annual checkup with Dr. Martinez',
  },
  {
    id: 'event-3',
    title: 'Sarah\'s Birthday',
    date: createDate(2),
    time: 'All Day',
    type: 'birthday',
    description: 'Send birthday wishes to Sarah!',
  },
  {
    id: 'event-4',
    title: 'Gym Session',
    date: createDate(2, 18, 0),
    time: '6:00 PM',
    type: 'reminder',
    description: 'Leg day workout',
  },
  {
    id: 'event-5',
    title: 'Client Presentation',
    date: createDate(3, 10, 0),
    time: '10:00 AM',
    type: 'meeting',
    description: 'Q4 product demo for stakeholders',
  },
  {
    id: 'event-6',
    title: 'Coffee with Mike',
    date: createDate(3, 15, 30),
    time: '3:30 PM',
    type: 'appointment',
    description: 'Catch up at Blue Bottle Coffee',
  },
  {
    id: 'event-7',
    title: 'Pay Rent',
    date: createDate(4),
    time: 'All Day',
    type: 'reminder',
    description: 'Monthly rent payment due',
  },
  {
    id: 'event-8',
    title: 'Code Review Session',
    date: createDate(4, 11, 0),
    time: '11:00 AM',
    type: 'meeting',
    description: 'Review PRs from this sprint',
  },
  {
    id: 'event-9',
    title: 'Dentist Cleaning',
    date: createDate(5, 13, 0),
    time: '1:00 PM',
    type: 'appointment',
    description: '6-month dental cleaning',
  },
  {
    id: 'event-10',
    title: 'Mom\'s Birthday',
    date: createDate(6),
    time: 'All Day',
    type: 'birthday',
    description: 'Call mom and send flowers',
  },
  {
    id: 'event-11',
    title: 'Yoga Class',
    date: createDate(6, 7, 0),
    time: '7:00 AM',
    type: 'reminder',
    description: 'Morning yoga at Zen Studio',
  },
  {
    id: 'event-12',
    title: 'Sprint Planning',
    date: createDate(7, 9, 0),
    time: '9:00 AM',
    type: 'meeting',
    description: 'Plan next 2-week sprint',
  },
  {
    id: 'event-13',
    title: 'Car Service',
    date: createDate(8, 16, 0),
    time: '4:00 PM',
    type: 'appointment',
    description: 'Oil change and tire rotation',
  },
  {
    id: 'event-14',
    title: 'Book Club Meeting',
    date: createDate(9, 19, 0),
    time: '7:00 PM',
    type: 'meeting',
    description: 'Discussing "Project Hail Mary"',
  },
  {
    id: 'event-15',
    title: 'Pick up Package',
    date: createDate(9),
    time: 'All Day',
    type: 'reminder',
    description: 'Package arriving at post office',
  },
  {
    id: 'event-16',
    title: 'Alex\'s Birthday Party',
    date: createDate(10, 20, 0),
    time: '8:00 PM',
    type: 'birthday',
    description: 'Birthday celebration at The Garden',
  },
  {
    id: 'event-17',
    title: 'Budget Review',
    date: createDate(11, 10, 30),
    time: '10:30 AM',
    type: 'meeting',
    description: 'Monthly finance meeting with leadership',
  },
  {
    id: 'event-18',
    title: 'Gym Session',
    date: createDate(11, 18, 0),
    time: '6:00 PM',
    type: 'reminder',
    description: 'Upper body workout',
  },
  {
    id: 'event-19',
    title: 'Hair Appointment',
    date: createDate(12, 11, 0),
    time: '11:00 AM',
    type: 'appointment',
    description: 'Haircut with Jamie',
  },
  {
    id: 'event-20',
    title: 'Weekend Hiking Trip',
    date: createDate(13, 8, 0),
    time: '8:00 AM',
    type: 'reminder',
    description: 'Pack gear and meet at trailhead',
  },
];

// Export default playlist
export const defaultPlaylist = mockTracks;
